import { requireAdmin } from "@/lib/session";
import { Sparkles, Wrench, Bug, Rocket, Settings2, GitCommitHorizontal } from "lucide-react";
import { UPDATES } from "@/lib/updates";
import AdminLayout from "@/components/admin/AdminLayout";
import buildHistoryJson from "@/lib/build-history.json";

export const revalidate = 0;

// ── Types ─────────────────────────────────────────────────────────────────────

type BuildCategory = "feat" | "fix" | "improve" | "refactor" | "chore" | "internal";

type BuildEntry = {
  build:     number;
  timestamp: string;
  subject:   string;
  hash:      string;
  category:  BuildCategory;
};

// build-history.json is auto-generated by .git/hooks/pre-push on every push.
const BUILD_HISTORY = buildHistoryJson as BuildEntry[];

// ── Category config ────────────────────────────────────────────────────────────

const CATEGORY_CONFIG: Record<BuildCategory, {
  label: string;
  Icon:  React.ComponentType<{ className?: string }>;
  color: string;
}> = {
  feat:     { label: "New Feature",  Icon: Rocket,    color: "text-emerald-600 bg-emerald-50 border-emerald-200" },
  fix:      { label: "Bug Fix",      Icon: Bug,       color: "text-rose-600 bg-rose-50 border-rose-200"          },
  improve:  { label: "Improvement",  Icon: Sparkles,  color: "text-sky-600 bg-sky-50 border-sky-200"             },
  refactor: { label: "Refactor",     Icon: Wrench,    color: "text-violet-600 bg-violet-50 border-violet-200"    },
  chore:    { label: "Internal",     Icon: Settings2, color: "text-stone-500 bg-stone-50 border-stone-200"       },
  internal: { label: "Internal",     Icon: Settings2, color: "text-stone-500 bg-stone-50 border-stone-200"       },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(iso: string) {
  return new Date(iso).toLocaleString("th-TH", {
    day:      "numeric",
    month:    "long",
    year:     "numeric",
    hour:     "2-digit",
    minute:   "2-digit",
    timeZone: "Asia/Bangkok",
  });
}

// Derive category from an updates.ts entry when no git entry exists (e.g. build #1).
function categoryFromUpdate(u: typeof UPDATES[0]): BuildCategory {
  const f = u.features?.length    ?? 0;
  const i = u.improvements?.length ?? 0;
  const x = u.fixes?.length        ?? 0;
  if (f > 0 && x === 0) return "feat";
  if (x > 0 && f === 0) return "fix";
  if (i > 0)            return "improve";
  return "internal";
}

// Merge build-history.json (auto, git-derived) with updates.ts (optional enrichment).
// Result is newest-first; every build in either source appears exactly once.
function getMergedHistory() {
  const map = new Map<number, { entry?: BuildEntry; update?: typeof UPDATES[0] }>();

  for (const entry of BUILD_HISTORY) {
    map.set(entry.build, { entry });
  }
  for (const update of UPDATES) {
    const existing = map.get(update.build) ?? {};
    map.set(update.build, { ...existing, update });
  }

  return Array.from(map.entries())
    .sort(([a], [b]) => b - a)
    .map(([build, data]) => ({ build, ...data }));
}

type MergedEntry = ReturnType<typeof getMergedHistory>[0];

// ── Sub-components ────────────────────────────────────────────────────────────

function CategoryBadge({ category }: { category: BuildCategory }) {
  const { label, Icon, color } = CATEGORY_CONFIG[category];
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold border ${color}`}>
      <Icon className="w-3 h-3" />
      {label}
    </span>
  );
}

function SectionLabel({ type }: { type: "features" | "improvements" | "fixes" }) {
  const MAP = {
    features:     { label: "ฟีเจอร์ใหม่", Icon: Rocket,   color: "text-emerald-600 bg-emerald-50 border-emerald-200" },
    improvements: { label: "ปรับปรุง",     Icon: Sparkles, color: "text-sky-600 bg-sky-50 border-sky-200"             },
    fixes:        { label: "แก้ไขบั๊ก",    Icon: Bug,      color: "text-rose-600 bg-rose-50 border-rose-200"          },
  } as const;
  const { label, Icon, color } = MAP[type];
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold border ${color}`}>
      <Icon className="w-3 h-3" />
      {label}
    </span>
  );
}

function BuildCard({ merged, isLatest }: { merged: MergedEntry; isLatest: boolean }) {
  const { entry, update } = merged;

  // Title: human-readable label from updates.ts first, then raw commit subject
  const title     = update?.title    ?? entry?.subject ?? `Build #${merged.build}`;
  const timestamp = entry?.timestamp ?? update?.timestamp ?? "";
  const category: BuildCategory =
    entry?.category ?? (update ? categoryFromUpdate(update) : "internal");

  // Show commit reference row when git data is available
  const showSubjectRef = !!entry && !!update?.title && entry.subject !== update.title;
  const hasEnrichment  = (update?.features?.length ?? 0) +
                         (update?.improvements?.length ?? 0) +
                         (update?.fixes?.length ?? 0) > 0;

  return (
    <div className={`relative bg-white rounded-2xl border shadow-sm overflow-hidden ${
      isLatest ? "border-orange-200" : "border-stone-100"
    }`}>
      {isLatest && (
        <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-orange-400 to-amber-400" />
      )}
      <div className="px-5 py-4">

        {/* Row 1: build badge · latest tag · category badge · timestamp */}
        <div className="flex items-start justify-between gap-3 mb-2.5">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`font-mono text-xs font-bold px-2.5 py-1 rounded-lg border ${
              isLatest
                ? "bg-orange-50 text-orange-600 border-orange-200"
                : "bg-stone-50 text-stone-500 border-stone-200"
            }`}>
              Build #{merged.build}
            </span>
            {isLatest && (
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-orange-500 text-white">
                ล่าสุด
              </span>
            )}
            <CategoryBadge category={category} />
          </div>
          {timestamp && (
            <time className="text-xs text-stone-400 shrink-0 pt-0.5">{formatDate(timestamp)}</time>
          )}
        </div>

        {/* Row 2: human-readable title */}
        <h2 className="text-sm font-semibold text-stone-800 mb-1.5 leading-snug">{title}</h2>

        {/* Row 3: commit subject + hash (when we have git data) */}
        {entry && (showSubjectRef ? (
          <div className="flex items-center gap-2 mb-3 min-w-0">
            <GitCommitHorizontal className="w-3.5 h-3.5 text-stone-300 shrink-0" />
            <span className="text-xs text-stone-400 truncate">{entry.subject}</span>
            <code className="text-[10px] text-stone-400 bg-stone-50 border border-stone-100 px-1.5 py-0.5 rounded font-mono shrink-0">
              {entry.hash}
            </code>
          </div>
        ) : (
          <div className="flex items-center gap-1.5 mb-3">
            <GitCommitHorizontal className="w-3.5 h-3.5 text-stone-300 shrink-0" />
            <code className="text-[10px] text-stone-400 bg-stone-50 border border-stone-100 px-1.5 py-0.5 rounded font-mono">
              {entry.hash}
            </code>
          </div>
        ))}

        {/* Rows 4+: optional bullet-point enrichment from updates.ts */}
        {hasEnrichment && (
          <div className="space-y-3">
            {(["features", "improvements", "fixes"] as const).map(type => {
              const items = update?.[type];
              if (!items?.length) return null;
              return (
                <div key={type}>
                  <div className="mb-1.5"><SectionLabel type={type} /></div>
                  <ul className="space-y-1">
                    {items.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs text-stone-600">
                        <span className="mt-1.5 w-1 h-1 rounded-full bg-stone-300 shrink-0" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function AdminUpdatesPage() {
  await requireAdmin();
  const merged = getMergedHistory();

  return (
    <AdminLayout title="Version History">
      <p className="text-sm text-stone-500 -mt-4 mb-6">
        ดูประวัติ Build, ฟีเจอร์ใหม่, การปรับปรุง และการแก้ไขระบบของ Recipe Vault
      </p>
      <div className="space-y-4">
        {merged.map((item, i) => (
          <BuildCard key={item.build} merged={item} isLatest={i === 0} />
        ))}
      </div>
    </AdminLayout>
  );
}
